set-option global tabstop 4
set-option global indentwidth 4
set-option global scrolloff 5,5
set-option global aligntab false
set-option global ui_options \
  terminal_set_title=false \
  terminal_assistant=none \
  terminal_enable_mouse=false \
  terminal_padding_char=
set-option global startup_info_version 99999999 # Disable startup message

colorscheme significance
hook global BufCreate .* %{
  add-highlighter buffer/ number-lines \
    -relative -hlcursor -separator '  ' -min-digits 4
  add-highlighter buffer/ show-matching
  add-highlighter buffer/ show-whitespaces \
    -lf ' ' -spc ' ' -nbsp '~' -tab '›' -tabpad '·'
  add-highlighter buffer/trailing-whitespaces regex "(\h+)$" 1:Error
}

hook global BufCreate .* %{
  editorconfig-load
  indent-config
}

hook global InsertCompletionShow .* %{
  map window insert <tab> <c-n>
  map window insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
  unmap window insert <tab> <c-n>
  unmap window insert <s-tab> <c-p>
}

source "%val{config}/clipboard.kak"
source "%val{config}/filetype.kak"
source "%val{config}/fzf.kak"
source "%val{config}/indent.kak"
source "%val{config}/modeline.kak"
source "%val{config}/tmux.kak"

map global user c     -docstring 'comment line'                         ':comment-line<ret>'
map global user C     -docstring 'comment block'                        ':comment-block<ret>'

map global user p     -docstring 'paste from clipboard after'           ':clipboard-paste-after<ret>'
map global user P     -docstring 'paste from clipboard before'          ':clipboard-paste-before<ret>'
map global user R     -docstring 'replace from clipboard'               ':clipboard-replace<ret>'
map global user y     -docstring 'yank selection to clipboard'          ':clipboard-yank-selection<ret>'
map global user Y     -docstring 'yank entire buffer to clipboard'      ':clipboard-yank-buffer<ret>'

map global user <a-c> -docstring 'change directory'                     ':fzf-cd<ret>'
map global user b     -docstring 'change buffer'                        ':fzf-buffer<ret>'
map global user <a-b> -docstring 'delete buffer'                        ':fzf-buffer-delete<ret>'
map global user f     -docstring 'edit file in git repository'          ':fzf-file-git<ret>'
map global user F     -docstring 'open file'                            ':fzf-file<ret>'
map global user <a-f> -docstring 'open file relative to current buffer' ':fzf-file-relative-to-buffer<ret>'

map global user <a-h> -docstring 'tmux horizontal split'                ':tmux-horizontal<ret>'
map global user <a-p> -docstring 'tmux popup'                           ':tmux-popup<ret>'
map global user <a-v> -docstring 'tmux vertical split'                  ':tmux-vertical<ret>'
map global user <a-w> -docstring 'tmux window'                          ':tmux-window<ret>'
