set-option global tabstop 4
set-option global indentwidth 4
set-option global scrolloff 3,0
set-option global aligntab false
set-option global ui_options \
  terminal_set_title=false \
  terminal_assistant=none \
  terminal_enable_mouse=false \
  terminal_padding_char=
set-option global startup_info_version 99999999 # Disable startup message

colorscheme uuu
hook global BufCreate .* %{
  add-highlighter buffer/ number-lines \
    -relative -hlcursor -separator '  ' -min-digits 4
  add-highlighter buffer/ show-matching
  add-highlighter buffer/ show-whitespaces \
    -lf ' ' -spc ' ' -nbsp '~' -tab '»' -tabpad '·'
  add-highlighter buffer/trailing-whitespaces regex "(\h+)$" 1:Error
}

hook global BufCreate .* %{
  editorconfig-load
  autoconfigtab
}

hook global InsertCompletionShow .* %{
  map window insert <tab> <c-n>
  map window insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
  unmap window insert <tab> <c-n>
  unmap window insert <s-tab> <c-p>
}

source "%val{config}/plugins.kak"
source "%val{config}/modeline.kak"
source "%val{config}/filetype.kak"

map global user c -docstring 'comment line' ':comment-line<ret>'
map global user C -docstring 'comment block' ':comment-block<ret>'

map global user p -docstring 'paste from clipboard after' ':kakclip-paste-after<ret>'
map global user P -docstring 'paste from clipboard before' ':kakclip-paste-before<ret>'
map global user R -docstring 'replace from clipboard' ':kakclip-replace<ret>'
map global user y -docstring 'yank selection to clipboard' ':kakclip-yank-selection<ret>'
map global user Y -docstring 'yank entire buffer to clipboard' ':kakclip-yank-buffer<ret>'
