#!/bin/sh

# Create a slug of the text on that is the concatenation of all command line
# arguments, or text piped into stdin.

set -e

slugify() {
  sed -E 's/[[:space:]]+/-/g' | sed 's/[^A-Za-z0-9_-]//g'
}

if [ "$#" -eq 0 ]; then
  slugify
else
  printf '%s' "$@" | slugify
fi
