#!/usr/bin/env python3

"""
Show the terminal dimensions on screen.
"""

import argparse
import os
import time

from dotfiles import keymonitor

parser = argparse.ArgumentParser(description='Show terminal dimensions')
parser.add_argument('-m', '--monitor',
  action='store_true',
  help='monitor the terminal dimensions')
args = parser.parse_args()

def show(newline=True):
  cols, lines = os.get_terminal_size()
  print(f"\r{9 * ' '}", end='')
  print(f"\r{cols} × {lines}", end='\n' if newline else '')

if args.monitor:
  with keymonitor() as km:
    while km.get() is None:
      show(newline=False)
      time.sleep(0.1)
    show()
else:
  show(newline=True)
