#!/bin/sh

# Show the dimensions of a terminal.

set -e

if [ "$#" -eq 0 ]; then
  printf "$(tput cols) × $(tput lines)\n"
else
  # Monitor mode that continuously outputs the size.
  while true; do
    printf "\r            \r$(tput cols) × $(tput lines)"
    sleep 0.1
  done
fi
