name: default
root: ~

startup_window: term

windows:
  - term:
      layout: even-horizontal
      panes:
        - # Terminal
        - # Terminal
  - music:
      panes: ncmpcpp
      root: ~/Music
  - dots:
      layout: even-horizontal
      panes:
        - # Terminal
        - # Terminal
      root: ~/.local/share/chezmoi
  - update:
      layout: even-horizontal
      panes:
        - # Terminal
        - # Terminal
