# Scripts in .chezmoiscripts will use this data to install the appropriate
# packages on a given platform.

[packages.macos]
brew = [
  "bat",
  "broot",
  "chezmoi",
  "editorconfig",
  "eza",
  "fd",
  "fish",
  "font-iosevka-term-nerd-font",
  "fzf",
  "ghostty",
  "git",
  "git-delta",
  "kakoune",
  "ranger",
  "ripgrep",
  "tmuxinator",
]

[packages.voidlinux]
xbps = [
  "ImageMagick",
  "alacritty",
  "alsa-utils",
  "atool",
  "bash",
  "bat",
  "broot",
  "bspwm",
  "chrony",
  "cronie",
  "curl",
  "delta",
  "dunst",
  "editorconfig",
  "eza",
  "fd",
  "fish-shell",
  "fzf",
  "gcc",
  "ghostty",
  "git",
  "gnome-keyring",
  "hsetroot",
  "kakoune",
  "kid3",
  "lightdm",
  "lightdm-gtk3-greeter",
  "make",
  "mpc",
  "mpd",
  "mpv",
  "ncmpcpp",
  "nerd-fonts",
  "numix-themes",
  "papirus-icon-theme",
  "pdf.js",
  "picom",
  "polybar",
  "python3",
  "qutebrowser",
  "ranger",
  "redshift",
  "ripgrep",
  "rofi",
  "ruby-tmuxinator",
  "screen",
  "scrot",
  "seahorse",
  "sxhkd",
  "sxiv",
  "tmux",
  "w3m-img",
  "wicd",
  "wicd-gtk",
  "wmname",
  "xdg-utils",
  "xdotool",
  "xfce4",
  "xprop",
  "xsel",
  "xset",
  "xsetroot",
  "zathura",
  "zathura-pdf-mupdf",
  "zenity",
]
