#!/usr/bin/env sh

# These are labels to show for different desktop states.
label_focused="●"
label_occupied="○"
label_empty="∙"

# All window IDs
wids=$(xprop -root -notype _NET_CLIENT_LIST | cut -d '#' -f 2 | tr "," "\n")

# The number of desktops
num_desks=$(xprop -root -notype _NET_NUMBER_OF_DESKTOPS | cut -d '=' -f 2)

# The current desktop
current_desk=$(xprop -root -notype _NET_CURRENT_DESKTOP | cut -d '=' -f 2)

# Get a list of all the occupied desktops
occupied=" "
for wid in $wids; do
    workspace=$(xprop -id $wid _NET_WM_DESKTOP | cut -d '=' -f 2)
    # The trailing space is important so that on a basic match results aren't
    # wrong. For example, "1" is in the string "8 9 10", but " 1 " is not in
    # " 8 9 10 "
    occupied="$occupied $workspace "
done

# Build the notificaiton
message=""
for i in $(seq 0 $(( num_desks - 1 ))); do
    if [ $i = $current_desk ]; then
        message="$message $label_focused"
    else
        case "$occupied" in
            *" $i "*) message="$message $label_occupied" ;;
            *)        message="$message $label_empty" ;;
        esac
    fi
done

notify-send -u low --hint=string:x-dunst-stack-tag:workspaces -a \
    "Workspaces" "$message"
