#!/usr/bin/env sh

# Shrink a window.

# Can be "left", "down", "right", "up"
dir="$1"

# The number of pixels to move the window
step=32

resize_xy() {
    case $dir in
        left)  echo -$step      0 ;;
        down)  echo      0 -$step ;;
        up)    echo      0 -$step ;;
        right) echo -$step      0 ;;
    esac
}

move_xy() {
    case $dir in
        left)  echo $step     0 ;;
        down)  echo     0     0 ;;
        up)    echo     0 $step ;;
        right) echo     0     0 ;;
    esac
}

berryc window_resize $(resize_xy)
berryc window_move   $(move_xy)
