#!/usr/bin/env sh

# If picom is running, send it a signal to reload its config, otherwise,
# start it
if pgrep picom; then
    pkill -USR1 picom
else
    pkill picom
    picom --config "$XDG_CONFIG_HOME/picom/picom.conf" &
fi
